packages:
  - packages/*

confirmModulesPurge: false

allowBuilds:
  esbuild: true

peerDependencyRules:
  allowedVersions:
    typescript: "7"

minimumReleaseAgeExclude:
  - "@jsr/readyrun__readyrun@0.1.0 || 0.1.1"
